spring.application.name=server

server.port=8081

#indicar duas propriedades para ele não fazer o registro da aplicação no serviço de descoberta
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
